# Generated by Django 5.2.6 on 2025-09-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.CharField(max_length=255)),
                ('number_field', models.IntegerField()),
                ('image_field', models.ImageField(upload_to='images/')),
                ('audio_field', models.FileField(upload_to='audio/')),
            ],
        ),
    ]
